# Generated by Django 5.1.7 on 2025-03-20 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Trip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("curr_location", models.CharField(max_length=100)),
                ("pick_location", models.CharField(max_length=100)),
                ("drop_location", models.CharField(max_length=100)),
                ("curr_cycle", models.BigIntegerField()),
            ],
        ),
        migrations.RenameModel(
            old_name="Item",
            new_name="Route",
        ),
        migrations.RenameField(
            model_name="route",
            old_name="description",
            new_name="content",
        ),
        migrations.RenameField(
            model_name="route",
            old_name="name",
            new_name="title",
        ),
    ]
