# Generated by Django 5.1.7 on 2025-03-20 16:06

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_trip_rename_item_route_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("hours_driven", models.PositiveIntegerField(default=0)),
                (
                    "fuel_stops",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of fuel stops: [{'mileage': float, 'location': str}]",
                    ),
                ),
                ("notes", models.TextField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="route",
            name="content",
        ),
        migrations.RemoveField(
            model_name="trip",
            name="curr_cycle",
        ),
        migrations.AddField(
            model_name="route",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="route",
            name="distance_miles",
            field=models.FloatField(default=0, help_text="Total distance in miles"),
        ),
        migrations.AddField(
            model_name="route",
            name="route_path",
            field=django.contrib.gis.db.models.fields.LineStringField(
                blank=True,
                help_text="GeoJSON or LineString for map route",
                null=True,
                srid=4326,
            ),
        ),
        migrations.AddField(
            model_name="route",
            name="stops",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of stops: [{'lat': float, 'lng': float, 'type': str}]",
            ),
        ),
        migrations.AddField(
            model_name="route",
            name="trip",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="routes",
                to="api.trip",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="trip",
            name="author",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="trips",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="trip",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="trip",
            name="cycle_hours",
            field=models.PositiveIntegerField(
                default=0, help_text="Current cycle used in hours"
            ),
        ),
        migrations.AlterField(
            model_name="trip",
            name="curr_location",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True,
                help_text="Current location as (longitude, latitude)",
                null=True,
                srid=4326,
            ),
        ),
        migrations.AlterField(
            model_name="trip",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="trip",
            name="drop_location",
            field=django.contrib.gis.db.models.fields.PointField(
                help_text="Dropoff location as (longitude, latitude)", srid=4326
            ),
        ),
        migrations.AlterField(
            model_name="trip",
            name="pick_location",
            field=django.contrib.gis.db.models.fields.PointField(
                help_text="Pickup location as (longitude, latitude)", srid=4326
            ),
        ),
        migrations.AddConstraint(
            model_name="trip",
            constraint=models.CheckConstraint(
                condition=models.Q(("cycle_hours__lte", 70)), name="max_70_hours"
            ),
        ),
        migrations.AddField(
            model_name="dailylog",
            name="route",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="logs",
                to="api.route",
            ),
        ),
    ]
